const sharp = require('sharp');

function escapeXml(text) {
  return String(text || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function normalizeColor(color) {
  if (!color || typeof color !== 'string') return '#000000';
  const normalized = color.trim();
  const match = normalized.match(/^#?([0-9A-Fa-f]{6})$/);
  return match ? `#${match[1]}` : '#000000';
}

function buildReceiptSvg({ businessName, businessAddress, receiptLines, total, receiptColor }) {
  const safeName = escapeXml(businessName || 'Your Business');
  const safeAddress = escapeXml(businessAddress || 'No address provided');
  const safeColor = normalizeColor(receiptColor);
  const lines = [
    `Receipt for ${safeName}`,
    safeAddress,
    '',
    ...receiptLines.map((line) => escapeXml(line)),
    '',
    `Total: ${escapeXml(total || 'N/A')}`,
  ];

  const width = 1200;
  const lineHeight = 48;
  const paddingTop = 120;
  const paddingBottom = 80;
  const height = paddingTop + paddingBottom + lines.length * lineHeight;
  const titleColor = safeColor;

  const textElements = lines
    .map((line, index) => {
      const y = paddingTop + index * lineHeight;
      return `<tspan x="60" dy="${index === 0 ? '0' : '1.2em'}">${line}</tspan>`;
    })
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="#ffffff" />
  <rect x="40" y="40" width="${width - 80}" height="${height - 80}" rx="28" fill="#f8f8f8" stroke="${titleColor}" stroke-width="4" />
  <text x="60" y="100" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="700" fill="${titleColor}">${escapeXml('RECEIPT')}</text>
  <text x="60" y="160" font-family="Arial, Helvetica, sans-serif" font-size="32" fill="#333333">${escapeXml('Business')}:</text>
  <text x="220" y="160" font-family="Arial, Helvetica, sans-serif" font-size="32" fill="#333333">${safeName}</text>
  <text x="60" y="210" font-family="Arial, Helvetica, sans-serif" font-size="24" fill="#666666">${safeAddress}</text>
  <text x="60" y="280" font-family="Arial, Helvetica, sans-serif" font-size="28" fill="#222222">
    ${textElements}
  </text>
  <rect x="60" y="${height - paddingBottom + 10}" width="${width - 120}" height="4" fill="${titleColor}" />
  <text x="60" y="${height - paddingBottom + 70}" font-family="Arial, Helvetica, sans-serif" font-size="32" font-weight="700" fill="#222222">Total: ${escapeXml(total || 'N/A')}</text>
  <text x="60" y="${height - paddingBottom + 120}" font-family="Arial, Helvetica, sans-serif" font-size="20" fill="#888888">Generated by FisiAI</text>
</svg>`;
}

async function createPdfFromJpegBuffer(jpegBuffer, width, height) {
  const header = Buffer.from('%PDF-1.3\n%\xFF\xFF\xFF\xFF\n');

  const contentsStream = `q\n${width} 0 0 ${height} 0 0 cm\n/Im0 Do\nQ\n`;

  const catalog = Buffer.from(`1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`);
  const pages = Buffer.from(`2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n`);
  const page = Buffer.from(`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /XObject << /Im0 4 0 R >> /ProcSet [/PDF /ImageC] >> /Contents 5 0 R >>\nendobj\n`);
  const image = Buffer.concat([
    Buffer.from(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpegBuffer.length} >>\nstream\n`),
    jpegBuffer,
    Buffer.from('\nendstream\nendobj\n'),
  ]);
  const contents = Buffer.from(`5 0 obj\n<< /Length ${Buffer.byteLength(contentsStream)} >>\nstream\n${contentsStream}endstream\nendobj\n`);

  const objects = [catalog, pages, page, image, contents];

  let pos = header.length;
  const xrefEntries = ['0000000000 65535 f \n'];
  for (const obj of objects) {
    xrefEntries.push(String(pos).padStart(10, '0') + ' 00000 n \n');
    pos += obj.length;
  }

  const xref = Buffer.from(`xref\n0 ${objects.length + 1}\n${xrefEntries.join('')}`);
  const trailer = Buffer.from(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${pos}\n%%EOF\n`);

  return Buffer.concat([header, ...objects, xref, trailer]);
}

async function generateReceiptAssets({ businessName, businessAddress, receiptText, total, receiptColor }) {
  const lines = receiptText
    ? receiptText.split(/\n|\r\n|\|/).map((line) => line.trim()).filter(Boolean)
    : ['No receipt details provided.'];

  const svg = buildReceiptSvg({
    businessName,
    businessAddress,
    receiptLines: lines,
    total,
    receiptColor,
  });

  const svgBuffer = Buffer.from(svg, 'utf8');
  const pngBuffer = await sharp(svgBuffer)
    .png()
    .toBuffer();

  const jpegBuffer = await sharp(svgBuffer)
    .jpeg({ quality: 90 })
    .toBuffer();

  const linesCount = lines.length;
  const height = 120 + 80 + linesCount * 48;
  const pdfBuffer = await createPdfFromJpegBuffer(jpegBuffer, 1200, height);

  return { pngBuffer, pdfBuffer };
}

function buildInvoiceSvg({ businessName, businessAddress, invoiceLines, total, receiptColor, invoiceNumber }) {
  const safeName = escapeXml(businessName || 'Your Business');
  const safeAddress = escapeXml(businessAddress || 'No address provided');
  const safeColor = normalizeColor(receiptColor);
  const safeInvoiceNumber = escapeXml(invoiceNumber || `INV-${Date.now()}`);
  const lines = [
    `Invoice Number: ${safeInvoiceNumber}`,
    `Date: ${new Date().toLocaleDateString()}`,
    '',
    `Bill To: ${safeName}`,
    safeAddress,
    '',
    ...invoiceLines.map((line) => escapeXml(line)),
    '',
    `Total Due: ${escapeXml(total || 'N/A')}`,
  ];

  const width = 1200;
  const lineHeight = 48;
  const paddingTop = 120;
  const paddingBottom = 80;
  const height = paddingTop + paddingBottom + lines.length * lineHeight;
  const titleColor = safeColor;

  const textElements = lines
    .map((line, index) => {
      return `<tspan x="60" dy="${index === 0 ? '0' : '1.2em'}">${line}</tspan>`;
    })
    .join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="#ffffff" />
  <rect x="40" y="40" width="${width - 80}" height="${height - 80}" rx="28" fill="#f8f8f8" stroke="${titleColor}" stroke-width="4" />
  <text x="60" y="100" font-family="Arial, Helvetica, sans-serif" font-size="42" font-weight="700" fill="${titleColor}">${escapeXml('INVOICE')}</text>
  <text x="60" y="160" font-family="Arial, Helvetica, sans-serif" font-size="32" fill="#333333">${escapeXml('Business')}:</text>
  <text x="220" y="160" font-family="Arial, Helvetica, sans-serif" font-size="32" fill="#333333">${safeName}</text>
  <text x="60" y="210" font-family="Arial, Helvetica, sans-serif" font-size="24" fill="#666666">${safeAddress}</text>
  <text x="60" y="280" font-family="Arial, Helvetica, sans-serif" font-size="28" fill="#222222">
    ${textElements}
  </text>
  <rect x="60" y="${height - paddingBottom + 10}" width="${width - 120}" height="4" fill="${titleColor}" />
  <text x="60" y="${height - paddingBottom + 70}" font-family="Arial, Helvetica, sans-serif" font-size="32" font-weight="700" fill="#222222">Total Due: ${escapeXml(total || 'N/A')}</text>
  <text x="60" y="${height - paddingBottom + 120}" font-family="Arial, Helvetica, sans-serif" font-size="20" fill="#888888">Generated by FisiAI</text>
</svg>`;
}

async function generateInvoiceAssets({ businessName, businessAddress, invoiceText, total, receiptColor, invoiceNumber }) {
  const lines = invoiceText
    ? invoiceText.split(/\n|\r\n|\|/).map((line) => line.trim()).filter(Boolean)
    : ['No invoice details provided.'];

  const svg = buildInvoiceSvg({
    businessName,
    businessAddress,
    invoiceLines: lines,
    total,
    receiptColor,
    invoiceNumber,
  });

  const svgBuffer = Buffer.from(svg, 'utf8');
  const pngBuffer = await sharp(svgBuffer)
    .png()
    .toBuffer();

  const jpegBuffer = await sharp(svgBuffer)
    .jpeg({ quality: 90 })
    .toBuffer();

  const svgHeight = 120 + 80 + lines.length * 48;
  const pdfBuffer = await createPdfFromJpegBuffer(jpegBuffer, 1200, svgHeight);

  return { pngBuffer, pdfBuffer };
}

module.exports = {
  generateReceiptAssets,
  generateInvoiceAssets,
};
